ALTER TABLE loans ADD COLUMN IF NOT EXISTS payout_id VARCHAR(255);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS provider_ref VARCHAR(255);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS failure_reason TEXT;
