// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MarketPay Engineering",
            "email": "engineering@marketpay.sl"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with email and password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_interfaces_http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_auth_application.TokenPair"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout and revoke all tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_interfaces_http.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_auth_application.TokenPair"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_interfaces_http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/loans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "List loans by state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_pkg_pagination.Response-github_com_marketpay_backend_internal_loan_domain_model_Loan"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Apply for a loan",
                "parameters": [
                    {
                        "description": "Loan application",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_loan_interfaces_http.applyLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/loans/vendor/{vendor_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "List loans for a specific vendor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vendor ID",
                        "name": "vendor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_pkg_pagination.Response-github_com_marketpay_backend_internal_loan_domain_model_Loan"
                        }
                    }
                }
            }
        },
        "/loans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Get loan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/loans/{id}/approve": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Approve a loan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review note",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_loan_interfaces_http.reviewLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/loans/{id}/disburse": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Disburse an approved loan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Monime reference",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_loan_interfaces_http.disburseLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/loans/{id}/reject": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Reject a loan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_loan_interfaces_http.rejectLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/loans/{id}/schedule": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Get repayment schedule for a loan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.RepaymentSchedule"
                            }
                        }
                    }
                }
            }
        },
        "/repayments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repayments"
                ],
                "summary": "Make a loan repayment",
                "parameters": [
                    {
                        "description": "Repayment data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_repayment_interfaces_http.repayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                        }
                    }
                }
            }
        },
        "/repayments/loans/{id}/default": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "repayments"
                ],
                "summary": "Mark a loan as defaulted",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reports/default-rate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Default rate report",
                "responses": {}
            }
        },
        "/reports/disbursement-volume": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Disbursement volume by month",
                "responses": {}
            }
        },
        "/reports/officer-queue": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Loan officer pending review queue",
                "responses": {}
            }
        },
        "/reports/partner-summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Partner loans and commission summary",
                "responses": {}
            }
        },
        "/reports/portfolio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Portfolio outstanding report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/repayment-rate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Repayment rate report",
                "responses": {}
            }
        },
        "/reports/vendor-distribution": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Vendor distribution by market",
                "responses": {}
            }
        },
        "/ussd": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "ussd"
                ],
                "summary": "Handle USSD request from gateway",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service Code",
                        "name": "serviceCode",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone Number",
                        "name": "phoneNumber",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Accumulated input",
                        "name": "text",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CON ... or END ...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vendors": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "List all vendors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "Register a new vendor",
                "parameters": [
                    {
                        "description": "Vendor data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_vendors_interfaces_http.createVendorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.Vendor"
                        }
                    }
                }
            }
        },
        "/vendors/market-associations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "List all market associations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.MarketAssociation"
                            }
                        }
                    }
                }
            }
        },
        "/vendors/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "Get vendor by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vendor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.Vendor"
                        }
                    }
                }
            }
        },
        "/vendors/{id}/eligibility": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "Check vendor loan eligibility",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vendor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/vendors/{id}/kyc/approve": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vendors"
                ],
                "summary": "Approve vendor KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vendor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.Vendor"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_marketpay_backend_internal_auth_application.TokenPair": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_marketpay_backend_internal_loan_domain_model.FundingSource": {
            "type": "string",
            "enum": [
                "MFI_PARTNER",
                "NGO_FUND",
                "BANK_PARTNER"
            ],
            "x-enum-varnames": [
                "FundingSourceMFIPartner",
                "FundingSourceNGOFund",
                "FundingSourceBankPartner"
            ]
        },
        "github_com_marketpay_backend_internal_loan_domain_model.InterestType": {
            "type": "string",
            "enum": [
                "FLAT",
                "DECLINING_BALANCE"
            ],
            "x-enum-varnames": [
                "InterestTypeFlat",
                "InterestTypeDecliningBalance"
            ]
        },
        "github_com_marketpay_backend_internal_loan_domain_model.Loan": {
            "type": "object",
            "properties": {
                "commission_paid": {
                    "type": "boolean"
                },
                "commission_rate": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_score_at_time": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "disbursed_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "frequency": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.RepaymentFrequency"
                },
                "funded_by": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.FundingSource"
                },
                "group_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interest_rate": {
                    "type": "number"
                },
                "interest_type": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.InterestType"
                },
                "loan_type": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.LoanType"
                },
                "monime_reference": {
                    "type": "string"
                },
                "outstanding_amount": {
                    "type": "number"
                },
                "partner_id": {
                    "type": "string"
                },
                "principal_amount": {
                    "type": "number"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "review_note": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.RepaymentSchedule"
                    }
                },
                "state": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.LoanState"
                },
                "term_weeks": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "vendor_id": {
                    "type": "string"
                }
            }
        },
        "github_com_marketpay_backend_internal_loan_domain_model.LoanState": {
            "type": "string",
            "enum": [
                "DRAFT",
                "PENDING_REVIEW",
                "AUTO_APPROVED",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "DISBURSED",
                "ACTIVE",
                "CLOSED",
                "DEFAULTED"
            ],
            "x-enum-varnames": [
                "LoanStateDraft",
                "LoanStatePendingReview",
                "LoanStateAutoApproved",
                "LoanStateUnderReview",
                "LoanStateApproved",
                "LoanStateRejected",
                "LoanStateDisbursed",
                "LoanStateActive",
                "LoanStateClosed",
                "LoanStateDefaulted"
            ]
        },
        "github_com_marketpay_backend_internal_loan_domain_model.LoanType": {
            "type": "string",
            "enum": [
                "EMERGENCY_ADVANCE",
                "STARTER_LOAN",
                "GROWTH_LOAN"
            ],
            "x-enum-varnames": [
                "LoanTypeEmergencyAdvance",
                "LoanTypeStarterLoan",
                "LoanTypeGrowthLoan"
            ]
        },
        "github_com_marketpay_backend_internal_loan_domain_model.RepaymentFrequency": {
            "type": "string",
            "enum": [
                "BIWEEKLY",
                "MONTHLY"
            ],
            "x-enum-varnames": [
                "RepaymentFrequencyBiweekly",
                "RepaymentFrequencyMonthly"
            ]
        },
        "github_com_marketpay_backend_internal_loan_domain_model.RepaymentSchedule": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "installment_no": {
                    "type": "integer"
                },
                "interest_due": {
                    "type": "number"
                },
                "is_grace_period": {
                    "type": "boolean"
                },
                "loan_id": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "penalty_amount": {
                    "type": "number"
                },
                "principal_due": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "total_due": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_marketpay_backend_internal_shared_domain_model.KYCStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "VERIFIED",
                "REJECTED"
            ],
            "x-enum-varnames": [
                "KYCPending",
                "KYCVerified",
                "KYCRejected"
            ]
        },
        "github_com_marketpay_backend_internal_shared_domain_model.Role": {
            "type": "string",
            "enum": [
                "SUPER_ADMIN",
                "ADMIN",
                "LOAN_OFFICER",
                "FIELD_AGENT",
                "VENDOR",
                "CUSTOMER",
                "MFI_PARTNER"
            ],
            "x-enum-varnames": [
                "RoleSuperAdmin",
                "RoleAdmin",
                "RoleLoanOfficer",
                "RoleFieldAgent",
                "RoleVendor",
                "RoleCustomer",
                "RoleMFIPartner"
            ]
        },
        "github_com_marketpay_backend_internal_vendors_domain_model.MarketAssociation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_marketpay_backend_internal_vendors_domain_model.Vendor": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_score": {
                    "type": "number"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "first_transaction_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kyc_status": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_shared_domain_model.KYCStatus"
                },
                "kyc_verified_at": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "market_association": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.MarketAssociation"
                },
                "market_association_id": {
                    "type": "string"
                },
                "national_id_number": {
                    "type": "string"
                },
                "national_id_type": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_vendors_domain_model.VendorStatus"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_marketpay_backend_internal_vendors_domain_model.VendorStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "ACTIVE",
                "SUSPENDED",
                "BLACKLISTED"
            ],
            "x-enum-varnames": [
                "VendorStatusPending",
                "VendorStatusActive",
                "VendorStatusSuspended",
                "VendorStatusBlacklist"
            ]
        },
        "github_com_marketpay_backend_pkg_pagination.Response-github_com_marketpay_backend_internal_loan_domain_model_Loan": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.Loan"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_auth_interfaces_http.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_auth_interfaces_http.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_auth_interfaces_http.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "phone",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_shared_domain_model.Role"
                }
            }
        },
        "internal_loan_interfaces_http.applyLoanRequest": {
            "type": "object",
            "required": [
                "amount",
                "frequency",
                "funded_by",
                "loan_type",
                "term_weeks"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "frequency": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.RepaymentFrequency"
                },
                "funded_by": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.FundingSource"
                },
                "group_id": {
                    "type": "string"
                },
                "loan_type": {
                    "$ref": "#/definitions/github_com_marketpay_backend_internal_loan_domain_model.LoanType"
                },
                "partner_id": {
                    "type": "string"
                },
                "term_weeks": {
                    "type": "integer"
                }
            }
        },
        "internal_loan_interfaces_http.disburseLoanRequest": {
            "type": "object",
            "required": [
                "monime_reference"
            ],
            "properties": {
                "monime_reference": {
                    "type": "string"
                }
            }
        },
        "internal_loan_interfaces_http.rejectLoanRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_loan_interfaces_http.reviewLoanRequest": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string"
                }
            }
        },
        "internal_repayment_interfaces_http.repayRequest": {
            "type": "object",
            "required": [
                "amount",
                "loan_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "loan_id": {
                    "type": "string"
                },
                "monime_reference": {
                    "type": "string"
                }
            }
        },
        "internal_vendors_interfaces_http.createVendorRequest": {
            "type": "object",
            "required": [
                "date_of_birth",
                "first_name",
                "last_name",
                "market_association_id",
                "national_id_number",
                "national_id_type",
                "phone",
                "pin"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "market_association_id": {
                    "type": "string"
                },
                "national_id_number": {
                    "type": "string"
                },
                "national_id_type": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MarketPay API",
	Description:      "MarketPay microfinance and USSD payment platform for informal market vendors in Sierra Leone.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
